// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeUserHandlerServer is an autogenerated mock type for the UnsafeUserHandlerServer type
type UnsafeUserHandlerServer struct {
	mock.Mock
}

// mustEmbedUnimplementedUserHandlerServer provides a mock function with given fields:
func (_m *UnsafeUserHandlerServer) mustEmbedUnimplementedUserHandlerServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeUserHandlerServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeUserHandlerServer creates a new instance of UnsafeUserHandlerServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeUserHandlerServer(t mockConstructorTestingTNewUnsafeUserHandlerServer) *UnsafeUserHandlerServer {
	mock := &UnsafeUserHandlerServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
